### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by AlanJIsaacson**

### CODE REVIEW

**Comment by simonrjones** [comment]
Comments:

**s24:wordpress-install**
- Can you install to get('webroot') . '/wordpress'

**s24:build-summary**
- I'd made [suggestions](https://github.com/studio24/deployer-recipes/pull/1) on renaming things, can you please respond to this. Copied below.

Can I suggest we use name_name format in JSON variables and group these up a bit more logically, e.g. environment, deploy_datetime, deployed_by, git_branch, git_commit
 
Can I suggest we use the ISO 8601 date for simplicity (it's also easier tro convert back into a datetime):

```
$now = new DateTime();
echo $now->format('c');
```

Update docs to use new shorter task name (s24:build-summary)

**`s24:check-branch**
- $main_branch does not work since not in function scope (in global scope)
- I recommend not asking users to setup config as variables, instead use set(). You can then access via get() in Deployer
- Alternatively, can you programmatically detect this? See https://davidwalsh.name/get-default-branch-name
- For the force option there's no need for a value, you can use InputOption::VALUE_NONE which should support:

```
dep deploy production --branch=hotfix --force
dep deploy production --branch=hotfix -m
```

Any reason the short version is `-m`?

**s24:disk-usage**
- Any reason you are running that command locally? Doesn't run() run remotely? Does this not work?

```
output()->write(run("df -kh"));
```

- Docs appear to reference incorrect task name
- Would be nice to have a title stating what this info is
- Is there a way to make this more human-readable? I presume we only need to know about one / or a few of these results?

**s24:confirm**
- Update task name in docs

**s24:show-summary**
- It's simpler to just use file_get_contents to return deploy build info

**s24:sync-down**
- Docs don't appear to show how to set config

**General**
We need some complete examples of deployment recipes, e.g. for WordPress. Can you write some up in docs please so we have a reference point to copy?

I presume its simpler to document examples rather than create a WordPress recipe - since its good to be able to customise for each project?

**Comment by simonrjones** [comment]
Defensive coding: you need to decide what to do if JSON file not available in s24:show-summary

E.g. display message saying there is no build summary.

**Comment by AlanJIsaacson** [comment]
Comments:

**s24:wordpress-install -updated**

Can you install to get('webroot') . '/wordpress'


**s24:build-summary - Updated**

I'd made suggestions on renaming things, can you please respond to this. Copied below.
Can I suggest we use name_name format in JSON variables and group these up a bit more logically, e.g. environment, deploy_datetime, deployed_by, git_branch, git_commit

Can I suggest we use the ISO 8601 date for simplicity (it's also easier tro convert back into a datetime):

$now = new DateTime();
echo $now->format('c');
Update docs to use new shorter task name (s24:build-summary)



**s24:check-branch - Updated**

$main_branch does not work since not in function scope (in global scope)
I recommend not asking users to setup config as variables, instead use set(). You can then access via get() in Deployer
Alternatively, can you programmatically detect this? See https://davidwalsh.name/get-default-branch-name
For the force option there's no need for a value, you can use InputOption::VALUE_NONE which should support:
dep deploy production --branch=hotfix --force
dep deploy production --branch=hotfix -m
Any reason the short version is -m?

**Now uses VALUE_NONE and default branch auto detected**

**s24:disk-usage -Updated**

Any reason you are running that command locally? Doesn't run() run remotely? Does this not work?
output()->write(run("df -kh"));
Docs appear to reference incorrect task name
Would be nice to have a title stating what this info is
Is there a way to make this more human-readable? I presume we only need to know about one / or a few of these results?

**s24:confirm -Updated**

Update task name in docs

**s24:show-summary -Updated**

It's simpler to just use file_get_contents to return deploy build info

**s24:sync-down -Updated**

Docs don't appear to show how to set config

**General - Sample deploy.php added with notes**
We need some complete examples of deployment recipes, e.g. for WordPress. Can you write some up in docs please so we have a reference point to copy?

I presume its simpler to document examples rather than create a WordPress recipe - since its good to be able to customise for each project?

**Comment by simonrjones** [comment]
Thanks @AlanJIsaacson, some notes to review next week.

I added some defensive code & supported the old and new build data variable formats.

I've updated show summary to make the output more compact, see this link for info on how to colourise output https://symfony.com/doc/current/console/coloring.html

Screenshot 2021-03-12 at 17 54 00

**Comment by simonrjones** [comment]
I moved the Slack notification & WP composer install in sub-folder to tasks as well - I presume these are both required? I tested the Slack one which works OK, can you please test `vendors-subpath`.

**Comment by simonrjones** [comment]
I've made suggested changes to examples/deploy.php for you to review in branch `deploy-example` (created from your code-review branch so we can merge back in there once done).

I've made quite a few changes, to simplify. I've only left local vars for things dev team may change - it seems simpler to keep host vars with the hosts() definition.

It may be useful to check the hosts & deployment flow setup against the docs at https://deployer.org/docs/hosts.html

I also added support for synching files or folders to the sync command, which I renamed to `sync` for convenience. This is a big change so I left that in the deploy-example branch too - so you can review it & decide whether its worth keeping. Chat Monday :)

**Comment by simonrjones** [comment]
Last comment! On my deploy-example I've removed the `target` config variable. 

Any tasks that use this:

```
$target = get('target');
```
Need updating to:
```
use Deployer\Task\Context;
$host = Context::get()->getHost();
```
// $host = deploy@hostname

See example: https://github.com/studio24/deployer-recipes/blob/deploy-example/src/sync.php

**Review by simonrjones — APPROVED** [review]

**Pull request merged**
